### PR TITLE
Update GmsCore and FakeStore

### PR DESCRIPTION
**Pull request by SuperITMan**

### CODE REVIEW

**Comment by dan-v** [comment]
thanks @SuperITMan. Two questions for you:
1. Can you confirm this has been built and is working for you without issues?
2. I'm trying to track down why there is a difference in the upstream sha256 for FakeStore. Any ideas?
```
# upstream https://microg.org/fdroid/repo/com.android.vending-22.apk
sha256sum com.android.vending-22.apk
91052e12866b867929f5f1ba27914b8cb365ce21d2f07e516f8c5ca930d9e5ce  com.android.vending-22.apk
# your repo
sha256sum com.android.vending-22.apk
2a1ebc997e0440e6855374ccf94e6d63ececc9dfbaa69bf048c837656a0ccadf  com.android.vending-22.apk
```

**Comment by davze** [comment]
`# SuperITMan
sha256sum com.android.vending-22.apk
2a1ebc997e0440e6855374ccf94e6d63ececc9dfbaa69bf048c837656a0ccadf  com.android.vending-22.apk`

This one is a html file of this page https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/tree/master/FakeStore and not the actual apk as it is supposed to be.

**Comment by dan-v** [comment]
@davze - thanks for tracking that down! @SuperITMan - happy to take a PR with this fixed and tested.

**Comment by davze** [comment]
@dan-v I can confirm that it works with the correct file.

**Comment by dan-v** [comment]
> @dan-v I can confirm that it works with the correct file.

Nice @davze. If you put up your own PR I'd be happy to accept that.

**Comment by dan-v** [comment]
Closing this out in favor of PR #10 as it fixed invalid FakeStore issue. Thanks for initial PR @SuperITMan. Happy to take more in the future.

**Pull request closed without merging**
